apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: rkalluru/frontend
      labels:
        app.kubernetes.io/name: frontend

---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
spec:
  containers:
    - name: catalogue
      image: rkalluru/catalogue
      labels:
        app.kubernetes.io/name: catalague

---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
spec:
  containers:
    - name: shipping
      image: rkalluru/shipping
      labels:
        app.kubernetes.io/name: shipping

---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
    - name: payment
      image: rkalluru/payment
      labels:
        app.kubernetes.io/name: payment

---
apiVersion: v1
kind: Pod
metadata:
  name: user
spec:
  containers:
    - name: user
      image: rkalluru/user
      labels:
        app.kubernetes.io/name: user
     

---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: rkalluru/cart
      labels:
        app.kubernetes.io/name: cart

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-roboshop
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-roboshop
spec:
  selector:
    app.kubernetes.io/name: catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cart-roboshop
spec:
  selector:
    app.kubernetes.io/name: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-roboshop
spec:
  selector:
    app.kubernetes.io/name: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: shipping-roboshop
spec:
  selector:
    app.kubernetes.io/name: shipping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: payment-roboshop
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      targetPort: 80